name: macinwind-monitoring
services:
  prom-server:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3005:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prom-server
      - loki

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-data:/loki

volumes:
  grafana-data:
  loki-data: 


# docker run -d -p 3005:3000 --name=grafana grafana/grafana-oss
#  docker run -d -p 3005:3000 --name=loki grafana/loki