name: Frontend CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: npm
          cache-dependency-path: web/frontend/package-lock.json

      - name: Install Dependencies
        working-directory: ./web
        run: npm ci

      - name: Next Build
        working-directory: ./web/frontend
        run: npm run build

      - name: ESLint
        working-directory: ./web/frontend
        run: npm run lint
