name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write 
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create placeholder .env file
        working-directory: ./desktop
        run: touch .env

      - name: Install dependencies
        working-directory: ./desktop
        run: npm install

      - name: Build and release
        working-directory: ./desktop
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release